import type { ThemeMode } from '../config';
import type { TestRun } from '../model/test-run';
import { escapeHtml } from './escape';

export interface LayoutOptions {
  title: string;
  reportTitle: string;
  activeNav: 'summary' | 'all-tests' | 'history';
  run: TestRun;
  theme: ThemeMode;
  basePath?: string;
  failedCount?: number;
}

function navHref(basePath: string | undefined, page: string): string {
  const prefix = basePath ? `${basePath}/` : '';
  return `${prefix}${page}`;
}

export function renderLayout(options: LayoutOptions, body: string): string {
  const { title, reportTitle, activeNav, run, theme, basePath, failedCount } = options;
  const ctx = run.context;
  const failures = failedCount ?? run.stats.failed;

  return `<!DOCTYPE html>
<html lang="en" data-default-theme="${escapeHtml(theme)}">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${escapeHtml(title)} — ${escapeHtml(reportTitle)}</title>
  <link rel="stylesheet" href="${navHref(basePath, 'assets/tokens.css')}"/>
  <link rel="stylesheet" href="${navHref(basePath, 'assets/report.css')}"/>
</head>
<body>
<div class="app-shell">
  <header class="top-nav">
    <div class="brand">${escapeHtml(reportTitle)}</div>
    <div style="display:flex;align-items:center;gap:12px">
      <button id="theme-toggle" class="theme-toggle" aria-label="Toggle theme" title="Toggle theme">◐</button>
      <a href="${escapeHtml(ctx.workflowUrl)}" class="btn" target="_blank" rel="noopener">Workflow</a>
    </div>
  </header>
  <div class="shell-body">
    <aside class="sidebar">
      <div class="sidebar-context">
        <div class="sidebar-context-title">${escapeHtml(ctx.workflow)}</div>
        <div class="sidebar-context-sub">Run #${ctx.runId}</div>
      </div>
      <nav class="sidebar-nav">
        <a class="nav-link ${activeNav === 'summary' ? 'active' : ''}" href="${navHref(basePath, 'index.html')}">Summary</a>
        <a class="nav-link ${activeNav === 'summary' && failures > 0 ? '' : ''}" href="${navHref(basePath, 'index.html')}#failures">
          Failures ${failures > 0 ? `<span class="nav-badge">${failures}</span>` : ''}
        </a>
        <a class="nav-link ${activeNav === 'all-tests' ? 'active' : ''}" href="${navHref(basePath, 'all-tests.html')}">All Tests</a>
        <a class="nav-link ${activeNav === 'history' ? 'active' : ''}" href="${navHref(basePath, '../index.html')}">History</a>
      </nav>
      <div style="border-top:1px solid var(--outline-variant);padding-top:12px;margin-top:12px">
        <a class="nav-link" href="${escapeHtml(ctx.repositoryUrl)}" target="_blank" rel="noopener">Repository</a>
        <a class="nav-link" href="https://github.com/mzbrau/actions-insights" target="_blank" rel="noopener">Source</a>
      </div>
    </aside>
    <main class="main-content">${body}</main>
  </div>
  <footer class="footer">
    <span>Generated by ${escapeHtml(reportTitle)}</span>
    <a href="${escapeHtml(ctx.commitUrl)}">${escapeHtml(ctx.commitShortSha)}</a>
    <span>${escapeHtml(ctx.author)}</span>
  </footer>
</div>
<script src="${navHref(basePath, 'assets/report.js')}" defer></script>
</body>
</html>`;
}
