import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro', 'setup/quick-start', 'setup/choose-outputs'],
    },
    {
      type: 'category',
      label: 'Setup Guide',
      collapsed: false,
      items: [
        'setup/prepare-test-output',
        'setup/add-action',
        'setup/pr-comments',
        'setup/workflow-summary',
        'setup/html-artifact',
        'setup/history-repository',
        'setup/example-workflows',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/configuration',
        'reference/architecture',
      ],
    },
    {
      type: 'category',
      label: 'History Repository',
      items: [
        {
          type: 'autogenerated',
          dirName: 'history-repository',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: ['development', 'contributing'],
    },
  ],
};

export default sidebars;
