import type { ActionConfig } from '../../src/config';
import type { TestRun } from '../../src/model/test-run';

export const sampleRun: TestRun = {
  id: '1',
  title: 'Actions Insights',
  status: 'failed',
  stats: {
    total: 3,
    passed: 1,
    failed: 1,
    skipped: 1,
    inconclusive: 0,
    durationMs: 1634,
    successRate: 50,
  },
  tests: [
    {
      id: 'pass',
      name: 'ShouldPass',
      fullName: 'SampleTests.ShouldPass',
      outcome: 'passed',
      durationMs: 123,
      assembly: 'SampleTests.dll',
      namespace: 'SampleTests',
      className: 'SampleTests',
      method: 'ShouldPass',
      attachments: [],
      traits: [],
      categories: [],
      retries: 0,
      sourceFile: 'sample.trx',
    },
    {
      id: 'fail',
      name: 'ShouldFail',
      fullName: 'SampleTests.ShouldFail',
      outcome: 'failed',
      durationMs: 1500,
      assembly: 'SampleTests.dll',
      namespace: 'SampleTests',
      className: 'SampleTests',
      method: 'ShouldFail',
      message: 'Expected true but was false',
      stackTrace: 'at SampleTests.ShouldFail() in SampleTests.cs:line 42',
      attachments: [],
      traits: [],
      categories: [],
      retries: 0,
      sourceFile: 'sample.trx',
      isNewFailure: true,
    },
    {
      id: 'skip',
      name: 'ShouldSkip',
      fullName: 'SampleTests.ShouldSkip',
      outcome: 'skipped',
      durationMs: 10,
      message: 'Skipped by attribute',
      attachments: [],
      traits: [],
      categories: [],
      retries: 0,
      sourceFile: 'sample.trx',
    },
  ],
  context: {
    repository: 'owner/repo',
    repositoryUrl: 'https://github.com/owner/repo',
    workflow: 'CI',
    workflowUrl: 'https://github.com/owner/repo/actions/runs/1',
    runId: 1,
    runAttempt: 1,
    branch: 'main',
    ref: 'refs/heads/main',
    prNumber: 42,
    prUrl: 'https://github.com/owner/repo/pull/42',
    commitSha: 'abc123def456',
    commitShortSha: 'abc123d',
    commitMessage: 'Fix tests',
    commitUrl: 'https://github.com/owner/repo/commit/abc123def456',
    author: 'octocat',
    actor: 'octocat',
    startedAt: '2026-01-01T12:00:00.000Z',
    completedAt: '2026-01-01T12:05:00.000Z',
  },
  sourceFiles: ['sample.trx'],
  reportPath: '_report',
};

export const sampleConfig: ActionConfig = {
  testResults: '**/*.trx',
  reportsSubdirectory: 'test-reports',
  commentMode: 'update',
  historyLimit: 20,
  retainDays: 30,
  reportTitle: 'Actions Insights',
  reportOutput: '_report',
  siteOutput: '_site',
  theme: 'auto',
  slowTestThresholdMs: 1000,
  githubToken: '',
  maxFailedTestsInComment: 10,
  maxFailedTestsInSummary: 20,
  maxStackTraceLines: 25,
  includeStdout: true,
  includeStderr: true,
  includeSlowestTests: 18,
  uploadHtmlReport: true,
  generateJobSummary: true,
  publishChecks: true,
  artifactRetentionDays: 30,
  includeRawTestResults: true,
  checkName: 'Actions Insights',
  history: {
    enabled: false,
    repository: '',
    token: '',
    branch: 'main',
    dataPath: 'data',
    repositoryName: 'owner/repo',
    mode: 'multi',
  },
  coverage: {
    enabled: false,
    files: '**/coverage.cobertura.xml',
    failIfMissing: false,
  },
};
